## Módulos

Vimos anteriormente como declarar funções no Python. Imagine que você queira reaproveitar uma função escrita no passado em um programa atual. Uma opção seria definir a função novamente. Agora imagine um projeto que envolverá várias etapas; ficaria inviável definir funções para todas as etapas. Felizmente, existe uma forma fácil de reaproveitar funções em Python. Um **módulo** nada mais é que um conjunto de scripts escritos na linguagem Python, que você pode "chamar" e utilizar as funções descritas nele.

Alguns exemplos de módulos muito utilizados para aplicações científicas em Python são: numpy, scipy, matplotlib, pandas e scikit-learn. Veremos exemplos deles em outros notebooks, mas hoje vamos dar ênfase no módulo Numpy.

[Documentação - Módulos](https://docs.python.org/pt-br/3/tutorial/modules.html)

### Importando um módulo

Existem várias formas de importar funções de um módulo. Como exemplo, imagine um módulo chamado `module` que possui diversas funções, entre elas, a função `function`.

- `import module`: com isso, todas as funções serão importadas. Para usar a função `function`, chamamos `module.function()`
- `import module as md`: com isso, todas as funções serão importadas, mas o módulo passa ser chamado `md` dentro do seu programa. Essa é uma forma comum de se importar módulos, para poder usar um nome menor para chamar suas funções. Para usar a função `function` nesse caso, chamamos `md.function()`
- `from module import function`: com isso, somente a função `function` é importada. Para usá-la, chamamos `function()`. Assim, fica mais fácil chamar a função, mas cuidado para que o nome dessa função não conflite com outras.
- `from module import *`: Isso importa todas as funções de um módulo, bastando usar seus nomes para chamá-las. Esse modo de importar funções não é recomendado, mas é possível vê-lo em alguns programas.

Cada módulo só é importado uma vez por sessão, portanto, importar o mesmo módulo várias vezes não fará efeito. 

Quando se escreve um script, é recomendado importar todos os módulos no início. Porém, em um Jupyter Notebook, é possível deixar a importação dos módulos para quando as funções forem utilizadas.

### Numpy

Numpy (Python numérico) é um módulo que possui uma funcionalidade que é a base de outros módulos, como scipy e pandas: o numpy.ndarray, ou array. Um array é como uma lista, mas com mais funcionalidades, e que permite cálculos mais rápidos. Vejamos como importar o numpy e trabalhar com arrays.

In [1]:
# Importar todo o módulo (forma menos usada, por isso, está incluída somente como comentário)
# import numpy

# Essa é uma forma muito comum de se importar o numpy, e é a que vamos usar
import numpy as np  

# Somente como exemplo, veja que podemos importar o numpy com qualquer nome, desde que não entre em conflito com outras funções do Python
# O import a seguir seria válido:
# import numpy as qualquer_nome_que_quiser

In [2]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [3]:
# A partir de uma lista guardada em uma variável
l = [1, 2, 3]
x = np.array(l)

In [4]:
# indexação
print(x[0])
print(x[-1])

1
3


In [5]:
y = np.arange(10)  # retorna um array começando em 0 e terminando em n-1, assim como a função range que vimos anteriormente
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a = np.linspace(0, 1, 4)  # array com 4 pontos igualmente espaçados entre 0 e 1
a

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [7]:
b = np.linspace(1, 5, 4) 
b

array([1.        , 2.33333333, 3.66666667, 5.        ])

Veja que os símbolos + e - funcionam de forma diferente das listas em Python:

In [8]:
print(a + b)
print(a - b)

[1.         2.66666667 4.33333333 6.        ]
[-1. -2. -3. -4.]


Também é possível fazer multiplicação e divisão

In [9]:
a = np.array([1, 2, 3])
print(a*a)
print(a*3)
print(a/10)

[1 4 9]
[3 6 9]
[0.1 0.2 0.3]


Matrizes

In [12]:
m1 = np.array([[9,2,8],[4,7,2],[3,4,4]])
# m1 = [[9,2,8],[4,7,2],[3,4,4]].reshape((3, 3))
m1

array([[9, 2, 8],
       [4, 7, 2],
       [3, 4, 4]])

In [13]:
m1.shape

(3, 3)

In [17]:
# Indexação em matrizes: mais de um índice 
print(m1[1])  # o item 1 é a linha 1
print(m1[0][0])  # item 0 da linha 0

[4 7 2]
9


Funcionalidades matemáticas estão disponíveis

In [19]:
print(np.sin(0))  # seno
print(np.cos(90))  # cosseno - note que o número está em radianos
print(np.pi)  # pi

0.0
-0.4480736161291701
3.141592653589793
