## Módulos

Vimos anteriormente como declarar variáveis e funções no Python. Imagine que você queira reaproveitar uma função escrita no passado em um programa atual. Uma opção seria definir a função novamente. Agora imagine um projeto que envolverá várias etapas; ficaria inviável definir funções para todas as etapas. Felizmente, existe uma forma fácil de reaproveitar variáveis e funções em Python. Um **módulo** nada mais é que um conjunto de scripts escritos na linguagem Python, que você pode "chamar" e utilizar o que estiver descrito nele.

Alguns exemplos de módulos muito utilizados para aplicações científicas em Python são: math, numpy, scipy, matplotlib, pandas e scikit-learn. Veremos exemplos deles em outros notebooks, mas hoje vamos dar ênfase nos módulos math e numpy.

[Documentação - Módulos](https://docs.python.org/pt-br/3/tutorial/modules.html)

[Tutorial - Kaggle](https://www.kaggle.com/colinmorris/working-with-external-libraries)

### Importando um módulo

Existem várias formas de importar funções de um módulo. Como exemplo, imagine um módulo chamado `module` que possui diversas funções, entre elas, a função `function`.

- `import module`: com isso, todas as funções serão importadas. Para usar a função `function`, chamamos `module.function()`
- `import module as md`: com isso, todas as funções serão importadas, mas o módulo passa ser chamado `md` dentro do seu programa. Essa é uma forma comum de se importar módulos, para poder usar um nome menor para chamar suas funções. Para usar a função `function` nesse caso, chamamos `md.function()`
- `from module import function`: com isso, somente a função `function` é importada. Para usá-la, chamamos `function()`. Assim, fica mais fácil chamar a função, mas cuidado para que o nome dessa função não conflite com outras.
- `from module import *`: Isso importa todas as funções de um módulo, bastando usar seus nomes para chamá-las. Esse modo de importar funções não é recomendado, mas é possível vê-lo em alguns programas.

Cada módulo só é importado uma vez por sessão, portanto, importar o mesmo módulo várias vezes não fará efeito. 

Quando se escreve um script, é recomendado importar todos os módulos no início. Porém, em um Jupyter Notebook, é possível deixar a importação dos módulos para quando as funções forem utilizadas.

### math

O módulo `math` expande as funcionlidades matemáticas disponíveis no Python. Vejamos:

In [1]:
import math

In [2]:
print(type(math))  # math é um objeto do tipo "módulo"

<class 'module'>


Podemos ver os nomes (variáveis e funções) definidas no módulo `math` usando `dir()`

In [3]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


Exemplos de variáveis definidas no módulo `math` são `pi` e `e` (número de Euler):

In [4]:
print(math.pi)
print(math.e)

3.141592653589793
2.718281828459045


Um exemplo de função definida no módulo `math` é a função logarítmica. Vejamos como usar essa função usando `help()`:

In [5]:
help(math.log)  # veja que não usamos os parênteses, somente o nome da função

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



Note que a função `log` aceita dois parâmetros: `x` e `base`. Se não definimos a base, o valor de `math.e` será usado, ou seja, a função retorna o logaritmo natural do número.

In [6]:
print(math.log(2))

0.6931471805599453


In [7]:
print(math.log(16, 2))  # logaritmo em base 2 do número 16

4.0


### Numpy

Numpy (Python numérico) é um módulo que possui uma funcionalidade que é a base de outros módulos, como scipy e pandas: o numpy.ndarray, ou array. Um array é como uma lista, mas com mais funcionalidades, e que permite cálculos mais rápidos. Vejamos como importar o numpy e trabalhar com arrays.

In [8]:
# Importar todo o módulo (essa forma é menos usada, por isso está incluída somente como comentário)
# import numpy

# Essa é uma forma muito comum de se importar o numpy, e é a que vamos usar
import numpy as np  

# Somente como exemplo, veja que podemos importar o numpy com qualquer nome, desde que não entre em conflito com outras funções do Python.
# O import a seguir seria válido:
# import numpy as qualquer_nome_que_quiser

**Criando um array**

In [9]:
# A partir de uma lista guardada em uma variável
l = [1, 2, 3]
x = np.array(l)
x

array([1, 2, 3])

In [10]:
# Ou diretamente a partir da lista declarada entre os parênteses da função np.array()
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [11]:
# Indexação
print(x[0])
print(x[-1])

1
3


In [12]:
y = np.arange(10)  # retorna um array começando em 0 e terminando em n-1, assim como a função range que vimos anteriormente
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a = np.linspace(0, 1, 5)  # array com 5 pontos igualmente espaçados entre 0 e 1
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
b = np.linspace(1, 5, 5) 
b

array([1., 2., 3., 4., 5.])

**Operações**

Veja que os símbolos + e - funcionam de forma diferente das listas em Python:

In [15]:
print(a + b)
print(a - b)

[1.   2.25 3.5  4.75 6.  ]
[-1.   -1.75 -2.5  -3.25 -4.  ]


Também é possível fazer multiplicação e divisão

In [16]:
a = np.array([1, 2, 3])
print(a*a)
print(a*3)
print(a/10)

[1 4 9]
[3 6 9]
[0.1 0.2 0.3]


**Matrizes**

In [17]:
m1 = np.array([[9,2,8],[4,7,2],[3,4,4]])
m1

array([[9, 2, 8],
       [4, 7, 2],
       [3, 4, 4]])

In [18]:
m1.shape

(3, 3)

In [19]:
# Indexação em matrizes: mais de um índice 
print(m1[1])  # o item 1 da matriz é a linha 1
print(m1[0][0])  # item 0 da linha 0

[4 7 2]
9


**Funcionalidades matemáticas**

In [20]:
print(np.sin(0))  # seno
print(np.cos(90))  # cosseno - note que o número está em radianos
print(np.pi)  # pi

0.0
-0.4480736161291701
3.141592653589793


**Submódulos**

Em alguns casos, fica muito confuso deixar todas as variáveis e funções em apenas um módulo. Felizmente, o Python permite a definição de módulos dentro de módulos (dentro de módulos, dentro de módulos...).

Por exemplo, podemos acessar o módulo `random` dentro de `numpy`: 

In [21]:
import numpy
print(type(numpy.random))

<class 'module'>


Ou podemos importar apenas o módulo que desejamos:

In [22]:
from numpy import random
print(type(random))  # note que aqui o módulo é chamado apenas pelo nome, sem o prefixo numpy.

<class 'module'>


Vamos usar uma função dentro do módulo random:

In [23]:
rolls = random.randint(low=1, high=6, size=10)
print(rolls)

[2 3 4 4 5 3 5 3 5 3]


In [24]:
print(type(rolls))

<class 'numpy.ndarray'>


Vemos que se trata de um array. Podemos usar `dir()` para verificar os métodos disponíveis:

In [25]:
dir(rolls)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

Para obter a média, podemos usar o método `.mean()`

In [26]:
print(rolls.mean())

3.7
